// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PH48831_C5_ASM.Models;

#nullable disable

namespace PH48831_C5_ASM.Migrations
{
    [DbContext(typeof(PH48831DbContext))]
    partial class PH48831DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.Combo", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboId"));

                    b.Property<decimal>("GiaCombo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenCombo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ComboId");

                    b.ToTable("Combos");

                    b.HasData(
                        new
                        {
                            ComboId = 1,
                            GiaCombo = 50000m,
                            TenCombo = "Combo Bữa Trưa"
                        },
                        new
                        {
                            ComboId = 2,
                            GiaCombo = 100000m,
                            TenCombo = "Combo Bữa Tối"
                        });
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.ComboChiTiet", b =>
                {
                    b.Property<int>("ComboChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboChiTietId"));

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("MonAnId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ComboChiTietId");

                    b.HasIndex("ComboId");

                    b.HasIndex("MonAnId");

                    b.ToTable("ComboChiTiets");

                    b.HasData(
                        new
                        {
                            ComboChiTietId = 1,
                            ComboId = 1,
                            MonAnId = 1,
                            SoLuong = 2
                        },
                        new
                        {
                            ComboChiTietId = 2,
                            ComboId = 1,
                            MonAnId = 2,
                            SoLuong = 1
                        },
                        new
                        {
                            ComboChiTietId = 3,
                            ComboId = 1,
                            MonAnId = 3,
                            SoLuong = 1
                        },
                        new
                        {
                            ComboChiTietId = 4,
                            ComboId = 2,
                            MonAnId = 4,
                            SoLuong = 1
                        },
                        new
                        {
                            ComboChiTietId = 5,
                            ComboId = 2,
                            MonAnId = 5,
                            SoLuong = 1
                        });
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.DiaChiQuan", b =>
                {
                    b.Property<int>("DiachiquanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiachiquanId"));

                    b.Property<string>("DiaChiChiTiet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DiachiquanId");

                    b.ToTable("diaChiQuans");

                    b.HasData(
                        new
                        {
                            DiachiquanId = 1,
                            DiaChiChiTiet = "Hà nội"
                        },
                        new
                        {
                            DiachiquanId = 2,
                            DiaChiChiTiet = "Hải phòng"
                        },
                        new
                        {
                            DiachiquanId = 3,
                            DiaChiChiTiet = "Hải Dương"
                        });
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.GioHang", b =>
                {
                    b.Property<int>("GioHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GioHangId"));

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GioHangId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.GioHangChiTiet", b =>
                {
                    b.Property<int>("GioHangChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GioHangChiTietId"));

                    b.Property<int?>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("GioHangId")
                        .HasColumnType("int");

                    b.Property<int?>("MonAnId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("GioHangChiTietId");

                    b.HasIndex("ComboId");

                    b.HasIndex("GioHangId");

                    b.HasIndex("MonAnId");

                    b.ToTable("GioHangChiTiets");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.HoaDon", b =>
                {
                    b.Property<int>("HoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonId"));

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TrangThaiHoaDonIdTrangThai")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiId")
                        .HasColumnType("int");

                    b.HasKey("HoaDonId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("TrangThaiHoaDonIdTrangThai");

                    b.HasIndex("TrangThaiId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.HoaDonChiTiet", b =>
                {
                    b.Property<int>("HoaDonChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonChiTietId"));

                    b.Property<int?>("ComboId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<int?>("MonAnId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("HoaDonChiTietId");

                    b.HasIndex("ComboId");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("MonAnId");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.Kichco", b =>
                {
                    b.Property<int>("KichCoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KichCoId"));

                    b.Property<string>("TenKichCo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KichCoId");

                    b.ToTable("kichcos");

                    b.HasData(
                        new
                        {
                            KichCoId = 1,
                            TenKichCo = "Lớn"
                        },
                        new
                        {
                            KichCoId = 2,
                            TenKichCo = "Nhỏ"
                        },
                        new
                        {
                            KichCoId = 3,
                            TenKichCo = "Trung Bình"
                        });
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.LoaiMonAn", b =>
                {
                    b.Property<int>("LoaiMonAnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiMonAnId"));

                    b.Property<string>("TenLoaiMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LoaiMonAnId");

                    b.ToTable("loaiMonAns");

                    b.HasData(
                        new
                        {
                            LoaiMonAnId = 1,
                            TenLoaiMon = "Đồ chay"
                        },
                        new
                        {
                            LoaiMonAnId = 2,
                            TenLoaiMon = "Thịt cá"
                        },
                        new
                        {
                            LoaiMonAnId = 3,
                            TenLoaiMon = "Món ăn khác"
                        });
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.MonAn", b =>
                {
                    b.Property<int>("MonAnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonAnId"));

                    b.Property<int>("DiachiquanId")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("KichCoId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiMonAnId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThanhPhanId")
                        .HasColumnType("int");

                    b.HasKey("MonAnId");

                    b.HasIndex("DiachiquanId");

                    b.HasIndex("KichCoId");

                    b.HasIndex("LoaiMonAnId");

                    b.HasIndex("ThanhPhanId");

                    b.ToTable("MonAns");

                    b.HasData(
                        new
                        {
                            MonAnId = 1,
                            DiachiquanId = 1,
                            Gia = 200000m,
                            HinhAnh = "/Images2/hosting-fpt-removebg-preview.png",
                            LoaiMonAnId = 3,
                            MoTa = "Pizza truyền thống",
                            TenMon = "Pizza",
                            ThanhPhanId = 1
                        },
                        new
                        {
                            MonAnId = 2,
                            DiachiquanId = 2,
                            Gia = 15000m,
                            HinhAnh = "/Images2/img-1000x600-1.jpg",
                            LoaiMonAnId = 1,
                            MoTa = "Bánh mì Việt Nam",
                            TenMon = "Bánh mì",
                            ThanhPhanId = 1
                        },
                        new
                        {
                            MonAnId = 3,
                            DiachiquanId = 3,
                            Gia = 60000m,
                            HinhAnh = "/Images2/istockphoto-1200064755-170667a.jpg",
                            LoaiMonAnId = 2,
                            MoTa = "Món bún nổi tiếng",
                            TenMon = "Bún bò Huế",
                            ThanhPhanId = 2
                        },
                        new
                        {
                            MonAnId = 4,
                            DiachiquanId = 1,
                            Gia = 50000m,
                            HinhAnh = "/Images2/istockphoto-1200064755-170667a.jpg",
                            LoaiMonAnId = 2,
                            MoTa = "Món phở truyền thống",
                            TenMon = "Phở",
                            ThanhPhanId = 3
                        },
                        new
                        {
                            MonAnId = 5,
                            DiachiquanId = 2,
                            Gia = 70000m,
                            HinhAnh = "/Images2/istockphoto-1200064755-170667a.jpg",
                            LoaiMonAnId = 2,
                            MoTa = "Gà rán giòn tan",
                            TenMon = "Gà rán",
                            ThanhPhanId = 2
                        },
                        new
                        {
                            MonAnId = 6,
                            DiachiquanId = 3,
                            Gia = 30000m,
                            HinhAnh = "/Images2/istockphoto-1200064755-170667a.jpg",
                            LoaiMonAnId = 1,
                            MoTa = "Bánh xèo giòn",
                            TenMon = "Bánh xèo",
                            ThanhPhanId = 1
                        },
                        new
                        {
                            MonAnId = 7,
                            DiachiquanId = 1,
                            Gia = 45000m,
                            HinhAnh = "/Images2/istockphoto-1200064755-170667a.jpg",
                            LoaiMonAnId = 2,
                            MoTa = "Hủ tiếu Nam Vang",
                            TenMon = "Hủ tiếu",
                            ThanhPhanId = 2
                        },
                        new
                        {
                            MonAnId = 8,
                            DiachiquanId = 2,
                            Gia = 120000m,
                            HinhAnh = "/Images2/istockphoto-1200064755-170667a.jpg",
                            LoaiMonAnId = 2,
                            MoTa = "Món sushi Nhật Bản",
                            TenMon = "Sushi",
                            ThanhPhanId = 3
                        },
                        new
                        {
                            MonAnId = 9,
                            DiachiquanId = 3,
                            Gia = 80000m,
                            HinhAnh = "/Images2/z6035875873720_114730cc66faa67749315b417c790719.jpg",
                            LoaiMonAnId = 3,
                            MoTa = "Mì Ý sốt cà chua",
                            TenMon = "Mì Ý",
                            ThanhPhanId = 1
                        },
                        new
                        {
                            MonAnId = 10,
                            DiachiquanId = 1,
                            Gia = 25000m,
                            HinhAnh = "/Images2/z6035875881929_d785375a00c2dabf615d911288f4930a.jpg",
                            LoaiMonAnId = 1,
                            MoTa = "Trà sữa truyền thống",
                            TenMon = "Trà sữa",
                            ThanhPhanId = 2
                        },
                        new
                        {
                            MonAnId = 11,
                            DiachiquanId = 2,
                            Gia = 30000m,
                            HinhAnh = "/Images2/z6042058761907_810f9203bd7cd908f0e8c873ab0bbfd3.jpg",
                            LoaiMonAnId = 1,
                            MoTa = "Salad rau củ tươi ngon",
                            TenMon = "Salad",
                            ThanhPhanId = 3
                        },
                        new
                        {
                            MonAnId = 12,
                            DiachiquanId = 3,
                            Gia = 20000m,
                            HinhAnh = "/Images2/z6042058820293_1b98c0f4626db7ed36546748783f2ca4.jpg",
                            LoaiMonAnId = 1,
                            MoTa = "Chè đậu xanh",
                            TenMon = "Chè",
                            ThanhPhanId = 1
                        });
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.ThanhPhan", b =>
                {
                    b.Property<int>("ThanhPhanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhPhanId"));

                    b.Property<string>("TenThanhPhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ThanhPhanId");

                    b.ToTable("thanhPhans");

                    b.HasData(
                        new
                        {
                            ThanhPhanId = 1,
                            TenThanhPhan = "Thịt gà, bột mì"
                        },
                        new
                        {
                            ThanhPhanId = 2,
                            TenThanhPhan = "Phô mai, cà chua"
                        },
                        new
                        {
                            ThanhPhanId = 3,
                            TenThanhPhan = "Thịt cá"
                        });
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.TrangThaiHoaDon", b =>
                {
                    b.Property<int>("IdTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrangThai"));

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTrangThai");

                    b.ToTable("TrangThaiHoaDons");

                    b.HasData(
                        new
                        {
                            IdTrangThai = 1,
                            TenTrangThai = "Đang xử lý"
                        },
                        new
                        {
                            IdTrangThai = 2,
                            TenTrangThai = "Đang giao"
                        },
                        new
                        {
                            IdTrangThai = 3,
                            TenTrangThai = "Đã giao"
                        },
                        new
                        {
                            IdTrangThai = 4,
                            TenTrangThai = "Đã thanh toán"
                        },
                        new
                        {
                            IdTrangThai = 5,
                            TenTrangThai = "Đã hủy"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PH48831_C5_ASM.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PH48831_C5_ASM.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PH48831_C5_ASM.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PH48831_C5_ASM.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.ComboChiTiet", b =>
                {
                    b.HasOne("PH48831_C5_ASM.Models.Combo", "Combo")
                        .WithMany("ComboChiTiets")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PH48831_C5_ASM.Models.MonAn", "MonAn")
                        .WithMany("ComboChiTiets")
                        .HasForeignKey("MonAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.GioHang", b =>
                {
                    b.HasOne("PH48831_C5_ASM.Models.ApplicationUser", "User")
                        .WithMany("GioHangs")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.GioHangChiTiet", b =>
                {
                    b.HasOne("PH48831_C5_ASM.Models.Combo", "Combo")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("ComboId");

                    b.HasOne("PH48831_C5_ASM.Models.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("GioHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PH48831_C5_ASM.Models.MonAn", "MonAn")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("MonAnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Combo");

                    b.Navigation("GioHang");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.HoaDon", b =>
                {
                    b.HasOne("PH48831_C5_ASM.Models.ApplicationUser", "User")
                        .WithMany("HoaDons")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PH48831_C5_ASM.Models.TrangThaiHoaDon", null)
                        .WithMany("HoaDons")
                        .HasForeignKey("TrangThaiHoaDonIdTrangThai");

                    b.HasOne("PH48831_C5_ASM.Models.TrangThaiHoaDon", "TrangThaiHoaDon")
                        .WithMany()
                        .HasForeignKey("TrangThaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrangThaiHoaDon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("PH48831_C5_ASM.Models.Combo", "Combo")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PH48831_C5_ASM.Models.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PH48831_C5_ASM.Models.MonAn", "MonAn")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MonAnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Combo");

                    b.Navigation("HoaDon");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.MonAn", b =>
                {
                    b.HasOne("PH48831_C5_ASM.Models.DiaChiQuan", "DiaChiQuan")
                        .WithMany("MonAns")
                        .HasForeignKey("DiachiquanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PH48831_C5_ASM.Models.Kichco", "Kichco")
                        .WithMany("MonAns")
                        .HasForeignKey("KichCoId");

                    b.HasOne("PH48831_C5_ASM.Models.LoaiMonAn", "LoaiMonAn")
                        .WithMany("MonAns")
                        .HasForeignKey("LoaiMonAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PH48831_C5_ASM.Models.ThanhPhan", "ThanhPhan")
                        .WithMany("MonAns")
                        .HasForeignKey("ThanhPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaChiQuan");

                    b.Navigation("Kichco");

                    b.Navigation("LoaiMonAn");

                    b.Navigation("ThanhPhan");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.ApplicationUser", b =>
                {
                    b.Navigation("GioHangs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.Combo", b =>
                {
                    b.Navigation("ComboChiTiets");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.DiaChiQuan", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.Kichco", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.LoaiMonAn", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.MonAn", b =>
                {
                    b.Navigation("ComboChiTiets");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.ThanhPhan", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("PH48831_C5_ASM.Models.TrangThaiHoaDon", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
